import turtle as t

t.speed(100)
t.shape('turtle')
def circle(n):
    for i  in range (180):
        t.forward(n)
        t.right(2)
def halfcircle(n):
    for i in range(89):
        t.forward(n)
        t.right(2)
def halfcircleb(n):
    for i in range(91):
        t.forward(n)
        t.left(2)
t.left(90)
t.begin_fill()
t.fillcolor('blue')
halfcircle(4)
t.right(90)
t.forward(229.16)
t.end_fill()
t.fillcolor('yellow')
t.begin_fill()
t.left(90)
halfcircleb(4)
t.end_fill()
t.penup()
t.goto(50, 45)
t.pendown()
t.fillcolor('white')
t.begin_fill()
circle(0.5)
t.end_fill()
t.penup()
t.goto(60, 45)
t.pendown()
t.fillcolor('black')
t.begin_fill()
circle(0.2)
t.end_fill()
t.penup()
t.goto(150, 45)
t.pendown()
t.fillcolor('white')
t.begin_fill()
circle(0.5)
t.end_fill()
t.fillcolor('black')
t.penup()
t.goto(155, 45)
t.pendown()
t.begin_fill()
circle(0.2)
t.end_fill()
t.penup()
t.goto(80, -50)
t.right(180)
t.width(5)
t.pencolor('red')
t.pendown()
halfcircleb(1.5)
t.hideturtle()
t.penup()
circle(100)